(()=>{const I={book:`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3"><path d="M9 12h18c4 0 5 3 5 6v34c0-4-3-6-7-6H9zM55 12H37c-4 0-5 3-5 6v34c0-4 3-6 7-6h16z"/></svg>`,eye:`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 32s10-16 27-16 27 16 27 16-10 16-27 16S5 32 5 32z"/><circle cx="32" cy="32" r="7"/></svg>`,file:`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3"><path d="M17 7h22l10 10v40H17zM39 7v12h12M24 30h18M24 38h18M24 46h13"/></svg>`,scale:`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3"><path d="M32 8v44M17 14h30M13 56h38M18 14 8 34h20L18 14zm28 0L36 34h20L46 14zM8 34c2 7 18 7 20 0M36 34c2 7 18 7 20 0"/></svg>`,target:`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3"><circle cx="32" cy="32" r="24"/><circle cx="32" cy="32" r="14"/><circle cx="32" cy="32" r="4"/><path d="M36 28 55 9M45 9h10v10"/></svg>`,chat:`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3"><path d="M9 12h46v32H29L17 54V44H9z"/><path d="M18 23h28M18 32h20"/></svg>`,camera:`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3"><path d="M8 20h13l5-7h12l5 7h13v32H8z"/><circle cx="32" cy="36" r="11"/></svg>`,pin:`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3"><path d="M32 58S14 42 14 26a18 18 0 1 1 36 0c0 16-18 32-18 32z"/><circle cx="32" cy="26" r="6"/></svg>`};
function person(role='boa'){let judge=role==='judge',ovj=role==='ovj',cit=role==='citizen';return `<svg class="role-svg" viewBox="0 0 190 260" aria-hidden="true"><ellipse cx="95" cy="242" rx="65" ry="10" fill="#dbe4f2"/><circle cx="95" cy="57" r="31" fill="#e7b996"/><path d="M63 52c2-29 57-36 64 1-17-11-47-10-64-1" fill="${cit?'#4b3540':'#26345e'}"/><path d="M56 105c21-23 58-23 79 0l16 106H39z" fill="${judge?'#202736':ovj?'#59627b':cit?'#d6a56f':'#13285c'}"/><path d="M72 101h46l-8 77H80z" fill="${judge?'#fff':cit?'#f3e5d7':'#dce6f5'}"/><path d="M48 121 21 192M142 121l27 71" stroke="#e7b996" stroke-width="18" stroke-linecap="round"/><path d="M51 209h88l11 42H40z" fill="${judge?'#202736':ovj?'#59627b':cit?'#b27a55':'#223b82'}"/>${judge?'<path d="M69 101h52l-10 25H79z" fill="#fff"/><path d="M87 101v25M103 101v25" stroke="#cbd1dc" stroke-width="2"/>':''}${role==='boa'?'<rect x="77" y="119" width="36" height="42" rx="5" fill="#eef3fb"/><text x="95" y="137" text-anchor="middle" font-size="11" font-family="Arial" font-weight="700" fill="#1a2a5e">BOA</text><path d="M83 147h24" stroke="#2d4099" stroke-width="3"/>':''}${ovj?'<path d="M74 118h42v54H74z" fill="#fff"/><path d="M82 129h26M82 139h26M82 149h18" stroke="#2d4099" stroke-width="3"/>':''}</svg>`}
function visual(type,title,sub){let art=type==='law'?`<div class="lawbook">${I.book}<b>Wetboek van<br>Strafrecht</b><span>Artikel 429ter</span></div>`:person(type);return `<section class="visual-hero ${type}"><div class="visual-copy"><span class="visual-kicker">${type==='law'?'WETTELIJK KADER':type==='judge'?'JURIDISCHE BEOORDELING':type==='ovj'?'DOSSIER EN VERVOLGING':'VAN WET NAAR PRAKTIJK'}</span><h3>${title}</h3><p>${sub}</p></div><div class="visual-art">${art}</div></section>`}
function chips(items){return `<div class="visual-chips">${items.map(([ic,t,s])=>`<div class="vchip"><span>${I[ic]}</span><div><b>${t}</b>${s?`<small>${s}</small>`:''}</div></div>`).join('')}</div>`}
function flow(){return `<div class="evidence-flow"><div>${I.eye}<b>Waarnemen</b></div><i>→</i><div>${I.file}<b>Proces-verbaal</b></div><i>→</i><div>${I.file}<b>OM</b></div><i>→</i><div>${I.scale}<b>Rechter</b></div></div>`}
function clearClasses(c){c.classList.remove('v-wide','v-goals','v-question','v-paired','v-law')}
function decorate(){const c=document.querySelector('#app > .card, main .card');if(!c)return;clearClasses(c);const text=(c.textContent||'').toLowerCase(),m=c.querySelector('.main');if(c.querySelector('.q-text,.opts')){c.classList.add('v-question');question(c,text);feedback(c);return}if(!m)return;const title=(m.querySelector('.ptitle')?.textContent||'').trim().toLowerCase();if(m.querySelector(':scope > figure,:scope > table,:scope > .illustratie,:scope > .infographic,:scope > .visual-wrap'))c.classList.add('v-wide');if(m.querySelectorAll(':scope > .kaart').length>=2)c.classList.add('v-paired');if(title.includes('leerdoelen'))c.classList.add('v-goals');if((text.includes('artikel 429ter')||text.includes('wettekst'))&&!text.includes('oefenvragen'))c.classList.add('v-law');if(m.dataset.visualized)return;m.dataset.visualized='1';let h='';
if(title.includes('leerdoelen')){h=visual('boa','Na dit onderwerp kun je:','De leerdoelen geven je houvast voor wat je straks in de praktijk moet herkennen en toepassen.')+chips([['target','Herkennen','Zie welke feiten juridisch relevant zijn.'],['eye','Beoordelen','Kijk naar gedrag én omstandigheden.'],['file','Vastleggen','Beschrijf objectieve feiten zorgvuldig.']]);}
else if(text.includes('artikel 429ter')||text.includes('wettekst')){h=visual('law','Artikel 429ter Sr','De letterlijke wettelijke basis blijft herkenbaar gescheiden van de uitleg in gewone taal.');}
else if(text.includes('jurisprudent')||text.includes('rechtbank')||text.includes('gerechtshof')||text.includes('rechter')){h=visual('judge','Hoe wordt dit juridisch beoordeeld?','Rechtspraak laat zien hoe feiten, omstandigheden en bewijs in concrete zaken worden gewogen.');}
else if(text.includes('officier van justitie')||text.includes('openbaar ministerie')){h=visual('ovj','Van proces-verbaal naar het OM','Een helder dossier maakt zichtbaar welke feiten zijn waargenomen en welke bronnen het bewijs ondersteunen.');}
else if(text.includes('proces-verbaal')||text.includes('verbalis')||text.includes('bewijs')){h=visual('boa','Kijk, luister en leg vast','Maak steeds onderscheid tussen je eigen waarneming, verklaringen en andere objectieve gegevens.')+chips([['eye','Eigen waarneming','Wat zag of hoorde je zelf?'],['chat','Verklaringen','Wie verklaart wat?'],['camera','Beelden','Welke objectieve beelden zijn er?'],['file','Proces-verbaal','Leg de feiten controleerbaar vast.']]);}
else if(text.includes('context')||text.includes('in de praktijk')||text.includes('herkenbare situatie')){h=visual('boa','Van wet naar straatpraktijk','Dezelfde gedraging kan door de concrete omstandigheden anders worden beoordeeld.')+chips([['pin','Plaats','Waar gebeurt het?'],['eye','Gedrag','Wat gebeurt er precies?'],['chat','Reactie','Wat wordt gezegd of gedaan?']]);}
else if(text.includes('kort samengevat')||text.includes('samenvatting')){h=chips([['book','Wet','Ken het juridisch kader.'],['eye','Waarnemen','Kijk naar concrete feiten.'],['file','Vastleggen','Schrijf controleerbaar op.'],['scale','Beoordelen','Weeg alle omstandigheden.']]);}
else if(title.includes('welkom')||title.includes('introduct')||text.includes('start de e-learning')){h=visual('boa','Seksuele straatintimidatie','Leer artikel 429ter Sr herkennen, juridisch beoordelen en zorgvuldig vastleggen in de dagelijkse praktijk.');}
if(h)m.insertAdjacentHTML('afterbegin',h);if((text.includes('bewijs')&&text.includes('rechter'))||(text.includes('proces-verbaal')&&text.includes('officier van justitie')))m.insertAdjacentHTML('beforeend',flow());}
function question(c,text){const q=c.querySelector('.q-text');if(!q||c.querySelector('.question-scene'))return;let scene=text.includes('praktijk')||text.includes('situatie')||text.includes('straat')?`<div class="scene-people"><div>${person('citizen')}</div><div class="scene-bubble">Lees eerst de feiten.<br><b>Wat is juridisch relevant?</b></div></div>`:`<div class="big-question">?</div>`;q.insertAdjacentHTML('beforebegin',`<section class="question-scene"><div><span class="visual-kicker">PRAKTIJKVRAAG</span><h3>Beoordeel de situatie</h3><p>Lees zorgvuldig. De afbeelding geeft het antwoord niet weg.</p></div>${scene}</section>`)}
function feedback(c){c.querySelectorAll('.fb').forEach(f=>{if(f.dataset.visualized)return;f.dataset.visualized='1';const ok=f.classList.contains('ok');f.insertAdjacentHTML('afterbegin',`<div class="result-banner ${ok?'good':'bad'}"><span>${ok?'✓':'×'}</span><div><b>${ok?'Juist antwoord':'Helaas, dat is niet het juiste antwoord.'}</b><small>${ok?'Bekijk hieronder waarom dit antwoord klopt.':'Bekijk hieronder het juiste antwoord en de uitleg.'}</small></div></div>`)})}
const l=document.createElement('link');l.rel='stylesheet';l.href='premium.css?v=3';document.head.appendChild(l);decorate();new MutationObserver(decorate).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});})();